RECENTDAYS parsing error
Fix for thread 'main' panicked at src/bin/choctaw_hog.rs:105:54:
Mismatch between definition and access of `RECENTDAYS`. Could not downcast to u32, need to downcast to alloc::string::String